# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Wed Nov  5 09:35:02 2025
#

import wx




class _676245580_wxFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((619, 727))
        self.SetTitle("frame_2")

        self.panel_1 = wx.Panel(self, -1)
        self.panel_1.SetMinSize((489, 496))
        self.panel_1.SetBackgroundColour(wx.Colour(216, 191, 216))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_20 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_20, 1, wx.EXPAND, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("F:\\CinePlusPriscila3A\\dulceria.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_20.Add(bitmap_4, 0, wx.EXPAND, 0)

        label_29 = wx.StaticText(self.panel_1, -1, "DULCERIA")
        label_29.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Elephant"))
        grid_sizer_20.Add(label_29, 0, wx.ALIGN_CENTER, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("F:\\CinePlusPriscila3A\\dulceria.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_20.Add(bitmap_5, 0, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(2, 1, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        lbPersonal = wx.StaticText(self.panel_1, -1, "Combo Personal:")
        lbPersonal.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Constantia"))
        grid_sizer_1.Add(lbPersonal, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, -1, "Palomitas chicas - Refresco chico.\n")
        label_1.SetMinSize((219, 37))
        label_1.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Constantia"))
        grid_sizer_2.Add(label_1, 0, 0, 0)

        self.spin_ctrl_1 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_2.Add(self.spin_ctrl_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_3 = wx.GridSizer(2, 1, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, -1, "Combo Pareja:")
        label_2.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Constantia"))
        grid_sizer_3.Add(label_2, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, -1, "Nachos medianos, Ref. mediano, sushi-12p.")
        label_3.SetMinSize((281, 19))
        label_3.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Constantia"))
        grid_sizer_4.Add(label_3, 0, 0, 0)

        self.spin_ctrl_2 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_4.Add(self.spin_ctrl_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_5 = wx.GridSizer(2, 1, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, -1, "Combo BFF:")
        label_4.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Constantia"))
        grid_sizer_5.Add(label_4, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_5.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, -1, "2 sandwich, 2 Ref. med, 2 dulces a elegir.")
        label_5.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Constantia"))
        grid_sizer_6.Add(label_5, 0, 0, 0)

        self.spin_ctrl_3 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_6.Add(self.spin_ctrl_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_7 = wx.GridSizer(2, 1, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, -1, u"Combo Niños:")
        label_6.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Constantia"))
        grid_sizer_7.Add(label_6, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_7.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, -1, "Palomitas chicas, Jugo chico (sabor a elegir).")
        label_7.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Constantia"))
        grid_sizer_8.Add(label_7, 0, 0, 0)

        self.spin_ctrl_4 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_8.Add(self.spin_ctrl_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_8 = wx.StaticText(self.panel_1, -1, "PIEZA UNICA")
        label_8.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Elephant"))
        sizer_1.Add(label_8, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_9 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        grid_sizer_10 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_9.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(self.panel_1, -1, "REFRESCOS")
        label_12.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Constantia"))
        grid_sizer_10.Add(label_12, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_11 = wx.FlexGridSizer(1, 6, 0, 0)
        grid_sizer_10.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.panel_1, -1, "Grande:")
        grid_sizer_11.Add(label_9, 0, 0, 0)

        self.spin_ctrl_5 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_11.Add(self.spin_ctrl_5, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, -1, "Mediano:")
        grid_sizer_11.Add(label_10, 0, 0, 0)

        self.spin_ctrl_6 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_11.Add(self.spin_ctrl_6, 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, -1, "Chico:")
        grid_sizer_11.Add(label_11, 0, 0, 0)

        self.spin_ctrl_7 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_11.Add(self.spin_ctrl_7, 0, 0, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("F:\\CinePlusPriscila3A\\refresco.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_9.Add(bitmap_1, 0, wx.EXPAND, 0)

        grid_sizer_12 = wx.FlexGridSizer(2, 7, 0, 0)
        sizer_1.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.panel_1, -1, "Sabor:")
        label_13.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Constantia"))
        grid_sizer_12.Add(label_13, 0, 0, 0)

        label_14 = wx.StaticText(self.panel_1, -1, "Naranja")
        label_14.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Constantia"))
        grid_sizer_12.Add(label_14, 0, 0, 0)

        self.spin_ctrl_8 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_12.Add(self.spin_ctrl_8, 0, 0, 0)

        label_15 = wx.StaticText(self.panel_1, -1, "Manzana")
        label_15.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Constantia"))
        grid_sizer_12.Add(label_15, 0, 0, 0)

        self.spin_ctrl_9 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_12.Add(self.spin_ctrl_9, 0, 0, 0)

        label_16 = wx.StaticText(self.panel_1, -1, "Coca-Cola")
        label_16.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Constantia"))
        grid_sizer_12.Add(label_16, 0, 0, 0)

        self.spin_ctrl_10 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_12.Add(self.spin_ctrl_10, 0, 0, 0)

        grid_sizer_12.Add((0, 0), 0, 0, 0)

        grid_sizer_13 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        grid_sizer_14 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_13.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        label_17 = wx.StaticText(self.panel_1, -1, "PALOMITAS")
        label_17.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Constantia"))
        grid_sizer_14.Add(label_17, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_15 = wx.FlexGridSizer(1, 6, 0, 0)
        grid_sizer_14.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        label_18 = wx.StaticText(self.panel_1, -1, "Grandes:")
        grid_sizer_15.Add(label_18, 0, 0, 0)

        self.spin_ctrl_11 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_15.Add(self.spin_ctrl_11, 0, 0, 0)

        label_19 = wx.StaticText(self.panel_1, -1, "Medianas:")
        grid_sizer_15.Add(label_19, 0, 0, 0)

        self.spin_ctrl_12 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_15.Add(self.spin_ctrl_12, 0, 0, 0)

        label_20 = wx.StaticText(self.panel_1, -1, "Chicas:")
        grid_sizer_15.Add(label_20, 0, 0, 0)

        self.spin_ctrl_13 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_15.Add(self.spin_ctrl_13, 0, 0, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("F:\\CinePlusPriscila3A\\palomitas.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_13.Add(bitmap_2, 0, wx.EXPAND, 0)

        grid_sizer_16 = wx.FlexGridSizer(1, 7, 0, 0)
        sizer_1.Add(grid_sizer_16, 1, wx.EXPAND, 0)

        label_21 = wx.StaticText(self.panel_1, -1, "Sabor:")
        label_21.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Constantia"))
        grid_sizer_16.Add(label_21, 0, 0, 0)

        label_22 = wx.StaticText(self.panel_1, -1, "Queso")
        label_22.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Constantia"))
        grid_sizer_16.Add(label_22, 0, 0, 0)

        self.spin_ctrl_14 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_16.Add(self.spin_ctrl_14, 0, 0, 0)

        label_23 = wx.StaticText(self.panel_1, -1, "Mantequilla")
        label_23.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Constantia"))
        grid_sizer_16.Add(label_23, 0, 0, 0)

        self.spin_ctrl_15 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_16.Add(self.spin_ctrl_15, 0, 0, 0)

        label_24 = wx.StaticText(self.panel_1, -1, "Natural")
        label_24.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Constantia"))
        grid_sizer_16.Add(label_24, 0, 0, 0)

        self.spin_ctrl_16 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_16.Add(self.spin_ctrl_16, 0, 0, 0)

        grid_sizer_17 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_17, 1, wx.EXPAND, 0)

        grid_sizer_18 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_17.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        label_25 = wx.StaticText(self.panel_1, -1, "NACHOS")
        label_25.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Constantia"))
        grid_sizer_18.Add(label_25, 0, 0, 0)

        grid_sizer_19 = wx.FlexGridSizer(1, 6, 0, 0)
        grid_sizer_18.Add(grid_sizer_19, 1, wx.EXPAND, 0)

        label_26 = wx.StaticText(self.panel_1, -1, "Grande:")
        grid_sizer_19.Add(label_26, 0, 0, 0)

        self.spin_ctrl_17 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_19.Add(self.spin_ctrl_17, 0, 0, 0)

        label_27 = wx.StaticText(self.panel_1, -1, "Mediano:")
        grid_sizer_19.Add(label_27, 0, 0, 0)

        self.spin_ctrl_18 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_19.Add(self.spin_ctrl_18, 0, 0, 0)

        label_28 = wx.StaticText(self.panel_1, -1, "Chico:")
        grid_sizer_19.Add(label_28, 0, 0, 0)

        self.spin_ctrl_19 = wx.SpinCtrl(self.panel_1, -1, "0", min=0, max=100)
        grid_sizer_19.Add(self.spin_ctrl_19, 0, 0, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("F:\\CinePlusPriscila3A\\nachos.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_17.Add(bitmap_3, 0, wx.EXPAND, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

