# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Oct 24 12:40:46 2025
#

import wx




class _557144905_wxFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((461, 564))
        self.SetTitle("frame_1")

        self.panel_1 = wx.Panel(self, -1)
        self.panel_1.SetBackgroundColour(wx.Colour(216, 191, 216))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("E:\\CinePlusPriscila3A\\taquilla.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, -1, "TAQUILLA")
        label_1.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Gill Sans Ultra Bold"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("E:\\CinePlusPriscila3A\\taquilla.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_RIGHT | wx.EXPAND, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, -1, "Pelicula:")
        label_2.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Georgia"))
        grid_sizer_3.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_3 = wx.StaticText(self.panel_1, -1, "Sala:")
        label_3.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Georgia"))
        grid_sizer_3.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_5 = wx.StaticText(self.panel_1, -1, "Horario:")
        label_5.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Georgia"))
        grid_sizer_3.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        grid_sizer_4 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.cmbPeli = wx.ComboBox(self.panel_1, -1, choices=["Blanca Nieves", "Wish", "Toy Story 4", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], style=wx.CB_DROPDOWN)
        grid_sizer_4.Add(self.cmbPeli, 0, 0, 0)

        lbSala = wx.StaticText(self.panel_1, -1, "--")
        lbSala.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Georgia"))
        grid_sizer_4.Add(lbSala, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        grid_sizer_8 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, -1, "00:00")
        grid_sizer_8.Add(self.rbHorario1, 0, 0, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, -1, "00:00")
        grid_sizer_8.Add(self.rbHorario2, 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, -1, "00:00")
        grid_sizer_8.Add(self.rbHorario3, 0, 0, 0)

        grid_sizer_8.Add((0, 0), 0, 0, 0)

        bmPelicula = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("E:\\CinePlusPriscila3A\\peli2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bmPelicula, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, -1, "BOLETOS")
        label_6.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Gill Sans Ultra Bold"))
        sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, -1, "Adultos ($80):")
        label_7.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Georgia"))
        grid_sizer_5.Add(label_7, 0, 0, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, -1, "")
        self.tfAdultos.SetMinSize((113, 23))
        grid_sizer_5.Add(self.tfAdultos, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, -1, "Menores ($70):")
        label_8.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Georgia"))
        grid_sizer_6.Add(label_8, 0, 0, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, -1, "")
        grid_sizer_6.Add(self.tfMenores, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_1, -1, "Subtotal: $")
        label_9.SetFont(wx.Font(12, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Georgia"))
        sizer_1.Add(label_9, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, -1, "Limpiar")
        self.btnLimpiar.SetMinSize((110, 35))
        self.btnLimpiar.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Gill Sans Ultra Bold"))
        self.btnLimpiar.SetBitmap(wx.Bitmap("D:\\CinePlusPriscila3A\\brocha.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSiguiente = wx.Button(self.panel_1, -1, "Siguiente")
        self.btnSiguiente.SetMinSize((110, 35))
        self.btnSiguiente.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Gill Sans Ultra Bold"))
        self.btnSiguiente.SetBitmap(wx.Bitmap("D:\\CinePlusPriscila3A\\flecha.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

