# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Tue Nov  4 07:14:16 2025
#

import wx




class _372242964_wxFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 363))
        self.SetTitle(u"inicio de sesión - CinePlus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("D:\\CinePlusPriscila3A\\logo.jfif", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, -1)
        self.panel_1.SetBackgroundColour(wx.Colour(124, 243, 163))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbTitulo = wx.StaticText(self.panel_1, -1, "Bienvenidos a CinePlus", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbTitulo.SetMinSize((132, 35))
        lbTitulo.SetFont(wx.Font(18, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Georgia"))
        sizer_1.Add(lbTitulo, 0, wx.EXPAND, 0)

        lbLogo = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("F:\\CinePlusPriscila3A\\logo.jfif", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(lbLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbUusario = wx.StaticText(self.panel_1, -1, "Usuario:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbUusario.SetMinSize((445, 20))
        lbUusario.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Georgia"))
        sizer_1.Add(lbUusario, 0, 0, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, -1, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbClave = wx.StaticText(self.panel_1, -1, u"Contraseña:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbClave.SetMinSize((445, 20))
        lbClave.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Georgia"))
        sizer_1.Add(lbClave, 0, 0, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, -1, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, -1, "Entrar")
        self.btnEntrar.SetMinSize((120, 35))
        self.btnEntrar.SetBackgroundColour(wx.Colour(0, 255, 0))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, -1, "Salir")
        self.btnSalir.SetMinSize((120, 35))
        self.btnSalir.SetBackgroundColour(wx.Colour(255, 0, 0))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        try:
            self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        except:
            print("could not bind event wx.EVT_BUTTON - ignoring error for preview")
        try:
            self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        except:
            print("could not bind event wx.EVT_BUTTON - ignoring error for preview")

    def confirmar_usuario_clave(self, event):
        print("Event handler 'confirmar_usuario_clave' not implemented!")
        event.Skip()

    def cerrar_programa(self, event):
        print("Event handler 'cerrar_programa' not implemented!")
        event.Skip()

